apiVersion: apps/v1
kind: Deployment
metadata:
  name: stake-cluster-deployment
  namespace: app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: stake
      version: "1"
  template:
    metadata:
      labels:
        app: stake
        version: "1"
    spec:
      volumes:
        - name: stake
          hostPath:
            path: /apps/RunningServer/Source/stake
        - name: common
          hostPath:
            path: /apps/RunningServer/Source/common
      initContainers:
        - name: jar
          tty: true
          image: cuongpct109/java-gradle:min
          imagePullPolicy: Always
          workingDir: /usr/src/stake
          command: ["gradle"]
          args: ["task", "jar", "--no-daemon"]
          volumeMounts:
            - name: stake
              mountPath: /usr/src/stake
            - name: common
              mountPath: /usr/src/common
        - name: build
          image: cuongpct109/java-gradle:min
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/stake
          command: ["gradle"]
          args: ["task", "copyJars", "--no-daemon"]
          volumeMounts:
            - name: stake
              mountPath: /usr/src/stake
            - name: common
              mountPath: /usr/src/common
        - name: copy-start
          image: cuongpct109/java-gradle:min
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/stake
          command: ["cp"]
          args:
            ["/usr/src/stake/scripts/start.sh", "/usr/src/stake/build/start.sh"]
          volumeMounts:
            - name: stake
              mountPath: /usr/src/stake
      containers:
        - name: stake
          image: cuongpct109/stake-base:latest
          imagePullPolicy: IfNotPresent
          tty: true
          volumeMounts:
            - name: stake
              mountPath: /usr/src/stake
          workingDir: /usr/src/stake/build
          command: ["bash"]
          args: ["start.sh"]
          # resources:
          #   limits:
          #     memory: "700Mi"
          #     cpu: "200m"
