apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-cluster-deployment
  namespace: app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: account
      version: "1"
  template:
    metadata:
      labels:
        app: account
        version: "1"
    spec:
      volumes:
        - name: account
          hostPath:
            path: /apps/RunningServer/Source/account
        - name: common
          hostPath:
            path: /apps/RunningServer/Source/common
      initContainers:
        - name: jar
          tty: true
          image: cuongpct109/java-gradle:min
          imagePullPolicy: Always
          workingDir: /usr/src/account
          restartPolicy: never
          command: ["gradle"]
          args: ["task", "jar", "--no-daemon"]
          volumeMounts:
            - name: account
              mountPath: /usr/src/account
            - name: common
              mountPath: /usr/src/common
        - name: build
          image: cuongpct109/java-gradle:min
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/account
          restartPolicy: never
          command: ["gradle"]
          args: ["task", "copyJars", "--no-daemon"]
          volumeMounts:
            - name: account
              mountPath: /usr/src/account
            - name: common
              mountPath: /usr/src/common
        - name: copy-start
          image: cuongpct109/java-gradle:min
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/account
          restartPolicy: never
          command: ["cp"]
          args:
            [
              "/usr/src/account/scripts/start.sh",
              "/usr/src/account/build/start.sh",
            ]
          volumeMounts:
            - name: account
              mountPath: /usr/src/account
      containers:
        - name: account
          image: cuongpct109/account-base:latest
          imagePullPolicy: IfNotPresent
          tty: true
          volumeMounts:
            - name: account
              mountPath: /usr/src/account
          workingDir: /usr/src/account/build
          command: ["bash"]
          args: ["start.sh"]
          resources:
            limits:
              memory: "1000Mi"
              cpu: "300m"
