apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-cluster-deployment
  namespace: app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bb
      version: "1"
  template:
    metadata:
      labels:
        app: bb
        version: "1"
    spec:
      volumes:
        - name: bb
          hostPath:
            path: /apps/RunningServer/Source/bb
        - name: common
          hostPath:
            path: /apps/RunningServer/Source/common
        # - name: bb-script
        #   hostPath:
        #     path: /apps/RunningServer/Source/bb/scripts/start-order.sh
        # - name: bb-log
        #   hostPath:
        #     path: /apps/RunningServer/logs/bb
      initContainers:
        - name: jar
          tty: true
          image: cuongpct109/bb-base:init
          workingDir: /usr/src/bb
          restartPolicy: never
          command: ["gradle"]
          args: ["task", "jar"]
          volumeMounts:
            - name: bb
              mountPath: /usr/src/bb
            - name: common
              mountPath: /usr/src/common
        - name: build
          image: cuongpct109/bb-base:init
          workingDir: /usr/src/bb
          restartPolicy: never
          command: ["gradle"]
          args: ["task", "copyJars"]
          volumeMounts:
            - name: bb
              mountPath: /usr/src/bb
            - name: common
              mountPath: /usr/src/common
        - name: copy-start
          image: cuongpct109/bb-base:init
          workingDir: /usr/src/bb
          restartPolicy: never
          command: ["cp"]
          args: ["/usr/src/bb/scripts/start.sh", "/usr/src/bb/build/start.sh"]
          volumeMounts:
            - name: bb
              mountPath: /usr/src/bb
      containers:
        - name: bb
          image: cuongpct109/bb-base:start
          imagePullPolicy: IfNotPresent
          tty: true
          volumeMounts:
            - name: bb
              mountPath: /usr/src/bb
          command: ["bash"]
          args: ["start.sh"]
          resources:
            limits:
              memory: "2000Mi"
              cpu: "1000m"
