apiVersion: v1
kind: Service
metadata:
  name: hibtc-web-cluster-loadbalancer
  namespace: api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hibtc-web
  type: LoadBalancer
  loadBalancerIP: 172.30.0.101
status:
  loadBalancer: {}
