apiVersion: v1
kind: Service
metadata:
  name: hibtc-web-cluster-nodeport
  namespace: api
spec:
  selector:
    app: hibtc-web
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
