apiVersion: v1
kind: Service
metadata:
  name: hibtc-web-cluster-ip-service
  namespace: api
  labels:
    app: hibtc-web
    cluster: "0"
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: hibtc-web
    cluster: "0"
    version: "1"
  ports:
    - name: http
      port: 8081
      targetPort: 8080
