apiVersion: v1
kind: Service
metadata:
  name: hibtc-back-cluster-ip-service
  namespace: admin
spec:
  type: ClusterIP
  selector:
    app: hibtc-back
    version: "1"
  ports:
    - port: 8085
      targetPort: 8085
  internalTrafficPolicy: Local
