apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-loadbalancer
  namespace: database
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer
  loadBalancerIP: 172.30.0.107
status:
  loadBalancer: {}
