apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
  namespace: database
  labels:
    app: redis
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: redis
    version: "1"
  ports:
    - name: tcp-6379
      port: 6379
      targetPort: 6379
