apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-properties
  namespace: database
data:
  broker.properties: |+
    brokerClusterName=rocketmq-cluster

    brokerName=broker-a

    brokerId=0

    namesrvAddr=rmqnamesrv-cluster-loadbalancer.database:9876

    brokerIP1=rmqbroker-cluster-loadbalancer.database
    brokerIP2=rmqbroker-cluster-loadbalancer.database

    defaultTopicQueueNums=4

    listenPort=10911

    deleteWhen=04

    fileReservedTime=120

    mapedFileSizeCommitLog=1073741824

    mapedFileSizeConsumeQueue=300000

    diskMaxUsedSpaceRatio=99

    maxMessageSize=65536

    brokerRole=ASYNC_MASTER

    flushDiskType=ASYNC_FLUSH

