apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-properties
  namespace: database
data:
  broker.properties: |+
    brokerClusterName=rocketmq-cluster

    brokerName=broker-a

    brokerId=0

    namesrvAddr=172.30.0.108:9876

    brokerIP1=172.30.0.109
    brokerIP2=172.30.0.109

    defaultTopicQueueNums=4

    listenPort=10911

    deleteWhen=04

    fileReservedTime=120

    mapedFileSizeCommitLog=1073741824

    mapedFileSizeConsumeQueue=300000

    diskMaxUsedSpaceRatio=99

    maxMessageSize=65536

    brokerRole=ASYNC_MASTER

    flushDiskType=ASYNC_FLUSH

