apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmqbroker-cluster-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmqbroker
      version: "1"
  template:
    metadata:
      labels:
        app: rmqbroker
        version: "1"
    spec:
      volumes:
        - name: log
          hostPath:
            path: /apps/RunningServer/Source/dbs/rocketmq/data/broker-master/logs
        - name: store
          hostPath:
            path: /apps/RunningServer/Source/dbs/rocketmq/data/broker-master/store
        - name: properties
          configMap:
            name: broker-properties
      containers:
        - name: rmqbroker
          image: cuongpct109/rocketmq-broker-base:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10909
            - containerPort: 10911
          volumeMounts:
            - name: log
              mountPath: /opt/logs
            - name: store
              mountPath: /opt/store
            - name: properties
              mountPath: /opt/conf/broker.properties
              subPath: broker.properties
