apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmqbroker-cluster-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmqbroker
      version: "1"
  template:
    metadata:
      labels:
        app: rmqbroker
        version: "1"
    spec:
      volumes:
        - name: script
          configMap:
            name: runbroker-customize
        - name: log
          hostPath:
            path: /apps/RunningServer/Source/dbs/rocketmq/data/broker-master/logs
        - name: store
          hostPath:
            path: /apps/RunningServer/Source/dbs/rocketmq/data/broker-master/store
        - name: broker-properties
          configMap:
            name: broker-properties
      containers:
        - name: rmqbroker
          image: cuongpct109/rocketmq-broker-base:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10909
            - containerPort: 10911
          volumeMounts:
            - name: script
              mountPath: /opt/rocketmq-4.9.4/bin/runbroker.sh
              subPath: runbroker.sh
            - name: log
              mountPath: /opt/logs
            - name: store
              mountPath: /opt/store
            - name: broker-properties
              mountPath: /opt/conf
              subPath: broker.properties
