apiVersion: apps/v1
kind: Deployment
metadata:
  name: hibtc-web-cluster-deployment-1
  namespace: api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: hibtc-web
      cluster: "1"
      version: "1"
  template:
    metadata:
      labels:
        app: hibtc-web
        cluster: "1"
        version: "1"
    spec:
      volumes:
        - name: hibtc-web-storage
          hostPath:
            path: /apps/RunningServer/Source/hibtc-web/build/libs/hibtc-web-0.0.1-SNAPSHOT/ROOT
        - name: hibtc-web-log
          hostPath:
            path: /apps/RunningServer/logs/hibtc-web/apps
        - name: hibtc-web-others-log
          hostPath:
            path: /apps/RunningServer/logs/hibtc-web/others
      containers:
        - name: hibtc-web
          image: cuongpct109/hibtc-web-base:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            initialDelaySeconds: 120
            periodSeconds: 30
          ports:
            - name: liveness-port
              containerPort: 8080
          volumeMounts:
            - name: hibtc-web-storage
              mountPath: /usr/local/tomcat/webapps/ROOT
            - name: hibtc-web-log
              mountPath: /usr/local/tomcat/hibtcLogs
            - name: hibtc-web-others-log
              mountPath: /usr/local/tomcat/logs
          resources:
            requests:
              memory: "600Mi"
            limits:
              memory: "600Mi"
