apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-nodeport
  namespace: database
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017
      protocol: TCP
