apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-cluster-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      version: "1"
  template:
    metadata:
      labels:
        app: mongo
        version: "1"
    spec:
      volumes:
        - name: mongo-init
          hostPath:
            path: /apps/RunningServer/Source/dbs/mongo/init
        - name: mongo-data
          hostPath:
            path: /apps/RunningServer/Source/dbs/mongo/data
        - name: mongo-data-var
          hostPath:
            path: /apps/RunningServer/Source/dbs/mongo/data/var
        - name: mongo-data-db
          hostPath:
            path: /apps/RunningServer/Source/dbs/mongo/data/db
        - name: mongoseed
          hostPath:
            path: /apps/RunningServer/Source/dbs/mongo/mongoseed
      containers:
        - name: mongo
          image: mongo:5.0.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
            - name: MONGO_INITDB_app
              value: "btc_log"
          volumeMounts:
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: mongo-data
              mountPath: /data
            - name: mongo-data-var
              mountPath: /var
            - name: mongo-data-db
              mountPath: /data/db
            - name: mongoseed
              mountPath: /mongoseed
              readOnly: true
