apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-cluster-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      cluster: "0"
      version: "1"
  template:
    metadata:
      labels:
        app: frontend
        cluster: "0"
        version: "1"
    spec:
      volumes:
        - name: app
          hostPath:
            path: /apps/RunningServer/Source/frontend
      # initContainers:
      #   - name: start-build
      #     tty: true
      #     image: node:16.18.1
      #     command: ["cd", "/app", &&, "yarn", "/app", "install"]
      #     volumeMounts:
      #       - name: app
      #         mountPath: /app
      containers:
        - name: frontend
          tty: true
          image: cuongpct109/frontend:init

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: liveness-port
          #   initialDelaySeconds: 120
          #   periodSeconds: 1
          # ports:
          #   - name: liveness-port
          #     containerPort: 3000
          volumeMounts:
            - name: app
              mountPath: /app
              # readOnly: true

          # resources:
          #   limits:
          #     memory: "200Mi"
          #     cpu: "100m"
