apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-cluster-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: app
          hostPath:
            path: /apps/RunningServer/Source/frontend
        - name: env-example
          configMap:
            name: env-example
      initContainers:
        - name: start
          tty: true
          image: node:16.18.1
          workingDir: /app
          command: ["yarn"]
          args: ["install"]
          volumeMounts:
            - name: app
              mountPath: /app
        - name: build
          image: node:16.18.1
          workingDir: /app
          command: ["yarn"]
          args: ["build"]
          volumeMounts:
            - name: app
              mountPath: /app
            - name: env-example
              mountPath: /app/.env.local
              subPath: .env.local
      containers:
        - name: frontend
          tty: true
          image: cuongpct109/frontend:dealing
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            initialDelaySeconds: 120
            periodSeconds: 1
          ports:
            - name: liveness-port
              containerPort: 3000
          volumeMounts:
            - name: app
              mountPath: /app
              readOnly: true
          # resources:
          #   limits:
          #     memory: "200Mi"
          #     cpu: "100m"
