apiVersion: v1
kind: Service
metadata:
  name: minio-cluster-nodeport
  namespace: database
spec:
  selector:
    app: minio
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
      protocol: TCP
