apiVersion: v1
kind: Service
metadata:
  name: minio-cluster-loadbalancer
  namespace: database
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
  type: LoadBalancer
  loadBalancerIP: 172.30.0.104
status:
  loadBalancer: {}
