apiVersion: v1
kind: Service
metadata:
  name: minio-cluster-ip-service
  namespace: database
  labels:
    app: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: tcp-9000
      port: 9000
      targetPort: 9000
    - name: tcp-9001
      port: 9001
      targetPort: 9001
