apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-loadbalancer
  namespace: database
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 27917
  selector:
    app: mongo
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 172.30.0.105
