apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip-service
  namespace: database
  labels:
    app: mongo
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: mongo
    version: "1"
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
