apiVersion: v1
kind: Service
metadata:
  name: hibtc-back-cluster-loadbalancer
  namespace: admin
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8085
  selector:
    app: hibtc-back
  type: LoadBalancer
  loadBalancerIP: 172.30.0.100
status:
  loadBalancer: {}
