apiVersion: v1
kind: Service
metadata:
  name: hibtc-back-cluster-ip-service
  namespace: api
  labels:
    app: hibtc-back
spec:
  type: ClusterIP
  selector:
    app: hibtc-back
  ports:
    - name: http
      port: 8081
      targetPort: 8080
