apiVersion: v1
kind: Service
metadata:
  name: hibtc-back-cluster-nodeport
  namespace: admin
spec:
  selector:
    app: hibtc-back
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
      protocol: TCP
