apiVersion: v1
kind: Service
metadata:
  name: hibtc-back-cluster-ip-service
  namespace: admin
  labels:
    app: hibtc-back
spec:
  type: ClusterIP
  selector:
    app: hibtc-back
  ports:
    - name: http
      port: 8085
      targetPort: 8085
