apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-ip-service
  namespace: database
  labels:
    app: zookeeper
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: zookeeper
    version: "1"
  ports:
    - name: tcp-client
      port: 2181
      targetPort: 2181
    - name: tcp-follower
      port: 2888
      targetPort: 2888
    - name: tcp-leader
      port: 3888
      targetPort: 3888
