apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-loadbalancer
  namespace: database
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 2181
  selector:
    app: zookeeper
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 172.30.0.110
