apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-nodeport
  namespace: database
  labels:
    app: zookeeper
spec:
  type: NodePort
  selector:
    app: rmqbroker
  ports:
    - port: 2181
      targetPort: 2181
      nodePort: 32181
      protocol: TCP
