apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-nodeport
  namespace: database
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30336
      protocol: TCP
