apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-nodeport
  namespace: database
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
      protocol: TCP
