apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-ip-service
  namespace: database
  labels:
    app: mysql
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: mysql
    version: "1"
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
