apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-loadbalancer
  namespace: database
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer
  loadBalancerIP: 172.30.0.106
status:
  loadBalancer: {}
