apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-nodeport
  namespace: api
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
      protocol: TCP
