apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-loadbalancer
  namespace: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30005
      targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 172.30.0.103
