apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip-service-1
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    cluster: "1"
    version: "1"
  ports:
    - name: http
      port: 3000
      targetPort: 3000
