apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-loadbalancer
  namespace: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
  loadBalancerIP: 172.30.0.103
status:
  loadBalancer: {}
