apiVersion: apps/v1
kind: Deployment
metadata:
  name: hibtc-web-socket-cluster-deployment-1
  namespace: api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: hibtc-web-socket
      cluster: "1"
      version: "1"
  template:
    metadata:
      labels:
        app: hibtc-web-socket
        cluster: "1"
        version: "1"
    spec:
      volumes:
        - name: hibtc-web-storage
          hostPath:
            path: /apps/RunningServer/Source/hibtc-web/build/libs/hibtc-web-socket-0.0.1-SNAPSHOT/ROOT
      containers:
        - name: hibtc-web-socket
          image: cuongpct109/hibtc-web-socket-base:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            initialDelaySeconds: 120
            periodSeconds: 30
          ports:
            - name: liveness-port
              containerPort: 8080
          volumeMounts:
            - name: hibtc-web-storage
              mountPath: /usr/local/tomcat/webapps/ROOT
          resources:
            requests:
              memory: "600Mi"
            limits:
              memory: "600Mi"
