apiVersion: v1
kind: ConfigMap
metadata:
  name: application-dev-web
  namespace: api
data:
  application-dev-web.properties: |
    spring.profiles.include=quartz-jp,staging-hosts

    #log
    logging.config=classpath:logback-config.xml

    #db
    db.web.dbUrl=jdbc:mysql://${mysql.host}:${mysql.port}/web?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.web.username=${mysql.username}
    db.web.password=${mysql.password}

    db.otc.dburl=jdbc:mysql://${mysql.host}:${mysql.port}/otc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.otc.username=${mysql.username}
    db.otc.password=${mysql.password}

    db.bb.dburl=jdbc:mysql://${mysql.host}:${mysql.port}/bb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.bb.username=${mysql.username}
    db.bb.password=${mysql.password}

    db.account.dbUrl=jdbc:mysql://${mysql.host}:${mysql.port}/account?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.account.username=${mysql.username}
    db.account.password=${mysql.password}

    db.chat.dbUrl=jdbc:mysql://${mysql.host}:${mysql.port}/chat_facet?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.chat.username=${mysql.username}
    db.chat.password=${mysql.password}

    db.mine.dbUrl=jdbc:mysql://${mysql.host}:${mysql.port}/mine?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.mine.username=${mysql.username}
    db.mine.password=${mysql.password}

    db.activity.dbUrl=jdbc:mysql://${mysql.host}:${mysql.port}/activity?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.activity.username=${mysql.username}
    db.activity.password=${mysql.password}

    db.config.dbUrl=jdbc:mysql://${mysql.host}:${mysql.port}/config?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db.config.username=${mysql.username}
    db.config.password=${mysql.password}

    mongo.dbname=btc_log
    mongo.host=${mongo.host}
    mongo.port=${mongo.port}
    mongo.username=${mongo.username}
    mongo.password=${mongo.password}
    mongo.slaveOk=false

    #redis
    redis.web.ip=${redis.host}
    redis.web.port=${redis.port}
    redis.web.timeout=2000
    redis.web.password=
    redis.web.database=0

    redis.account.ip=${redis.host}
    redis.account.port=${redis.port}
    redis.account.timeout=2000
    redis.account.password=
    redis.account.database=1

    redis.otc.ip=${redis.host}
    redis.otc.port=${redis.port}
    redis.otc.timeout=2000
    redis.otc.password=
    redis.otc.database=5

    redis.notify.ip=${redis.host}
    redis.notify.port=${redis.port}
    redis.notify.timeout=2000
    redis.notify.password=
    redis.notify.database=0

    redis.bb.ip=${redis.host}
    redis.bb.port=${redis.port}
    redis.bb.timeout=2000
    redis.bb.password=
    redis.bb.database=3

    redis.bbHistory.ip=${redis.host}
    redis.bbHistory.port=${redis.port}
    redis.bbHistory.timeout=2000
    redis.bbHistory.password=
    redis.bbHistory.database=3

    redis.bbBook.ip=${redis.host}
    redis.bbBook.port=${redis.port}
    redis.bbBook.timeout=2000
    redis.bbBook.password=
    redis.bbBook.database=2

    redis.bbCandle.ip=${redis.host}
    redis.bbCandle.port=${redis.port}
    redis.bbCandle.timeout=2000
    redis.bbCandle.password=
    redis.bbCandle.database=2

    redis.bbTicker.ip=${redis.host}
    redis.bbTicker.port=${redis.port}
    redis.bbTicker.timeout=2000
    redis.bbTicker.password=
    redis.bbTicker.database=2

    redis.funds.ip=${redis.host}
    redis.funds.port=${redis.port}
    redis.funds.timeout=2000
    redis.funds.password=
    redis.funds.database=10

    redis.mine.ip=${redis.host}
    redis.mine.port=${redis.port}
    redis.mine.timeout=2000
    redis.mine.password=
    redis.mine.database=10

    redis.report.ip=${redis.host}
    redis.report.port=${redis.port}
    redis.report.timeout=2000
    redis.report.password=
    redis.report.database=9

    redis.ticker.ip=${redis.host}
    redis.ticker.port=${redis.port}
    redis.ticker.timeout=2000
    redis.ticker.password =
    redis.ticker.database=2

    redis.settings.ip=${redis.host}
    redis.settings.port=${redis.port}
    redis.settings.timeout=2000
    redis.settings.password=
    redis.settings.database=8

    redis.statics.ip=${redis.host}
    redis.statics.port=${redis.port}
    redis.statics.timeout=2000
    redis.statics.password=
    redis.statics.database=9

    redis.activity.ip=${redis.host}
    redis.activity.port=${redis.port}
    redis.activity.timeout=2000
    redis.activity.password =
    redis.activity.database=4

    redis.monitor.ip=${redis.host}
    redis.monitor.port=${redis.port}
    redis.monitor.timeout=2000
    redis.monitor.password =
    redis.monitor.database=6

    #server
    server.web=1
    server.webSocket=0
    server.webApi=0
    server.test=1
    server.partner=0
    server.gm=0
    server.imgRealPath=/root/btc/web/img/files
    server.imgInternetPath=http://39.104.88.237:8088/img/files/
    server.accountDbName=account

    #dubbo
    #dubbo.zkAddress=zookeeper://127.0.0.1:2181?backup=127.0.0.1:2281,127.0.0.1:2381
    dubbo.zkAddress = ${zk.address}
    #dubbo.zkAddress=zookeeper://127.0.0.1:2181?backup=127.0.0.1:2281,127.0.0.1:2381
    dubbo.serverName=web
    dubbo.port=8283
    dubbo.timeout=20000
    dubbo.bbDubboDumpDirectory=dubbo

    #rocket mq
    mq.instanceName=consumer_web_
    mq.namesvrAddr=${mq.namesvrAddr}
    #mq.namesvrAddr=127.0.0.1:9886;127.0.0.1:9896
    mq.groupName=web-consumer
    mq.batchSize=2000

    #sms
    sms.TWILIO_SID=
    sms.TWILIO_TOKEN=
    sms.TWILIO_FROMPHONE=
    sms.register.MSG_INFO=
    sms.login.MSG_INFO=${sms.register.MSG_INFO}
    sms.resetPassword.MSG_INFO=${sms.register.MSG_INFO}

    USE_OSS=false
    USE_FILES=false

    aws.ACCESS_KEY=AKIAWC7KSIG76KXWPGVA
    aws.SECRET_KEY=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
    aws.BUCKET_NAME_WEB=koindex-dev-web
    aws.BUCKET_NAME_INNER=koindex-dev-inner

    aws.sns.ACCESS_KEY=AKIAWC7KSIG7WUNN667H
    aws.sns.SECRET_KEY=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
    aws.sns.REGION=ap-northeast-1
    aws.sns.ARN_URL=arn:aws:sns:ap-northeast-1:418714370495:koindex-test

    server.testtool_open=false

    NOTICE_URL=http://www.exonline.club.com/

    #legit domain for each dealing
    dealing.domain=deadling1.org
    GOOGLE_FORMAT=otpauth://totp/%s?secret=%s&issuer=${dealing.domain}

    specific.preNickname=DEALING

    USE_S3_MSG_SERVER=true
    SUPPORT_FOR_CHINA_USER=false


    USRE_IMG_PAGE =/consumer/get/img?urlImg=

    SYS_FLAG=true

    IS_NEW_KOR_REG=false

    nice.sSiteCode=
    nice.sSitePassword=
    nice.sReturnUrl=https://web.exonline.club.com/checkphone/sucess
    nice.sErrorUrl=https://web.exonline.club.com/checkphone/failed
    nice.niceUid=
    nice.svcPwd=

    #Zendesk SSO
    zendesk.SHARED_KEY=
    zendesk.SUBDOMAIN=

    time.timeDiff=-14400000
    mine.coinPrice=0.02
    IS_KRW_PRICE_FLAG=false
    noTradeNoRebate=false
    validate.switch=true
    login.disable_phone=false
    IS_JP=true
    IS_JP_AUTO_MINE=false
    partner.new_switch=true

    #Get price prom other market service
    getOtherPrice.start=true
    coinMarketCapSchedule=0 * * * * ?
    coinMarketCap.key=7bcf3ab8-b613-4bc5-8ac3-6b73a668d27d
    metalsApiSchedule=0 */10 * * * ?
    metalsApi.key=ayuje335ec984o38q17srxup90a3lkyqylbwb0n5shpf05e3m11wty5oj4pu
    koinIndexSchedule=0 * * * * ?
    koinIndex.key=ZGV2QGV4YW1wbGUuY29tOk1XdV5iQHQxem9IMA

    # Update Currency Rates service control flag
    updateCurrencyRates.start=false
    # Payment service control flag
    paymentSchedule.start=false

    # OneZero Alert Job control flag
    oneZeroAlertJob.start=false

    # X-Wallet
    xwallet.domain=http://${xwallet.host}:${xwallet.port}
    xwallet.api=/api/v1
    # api-key ultorex_super_user_on_testnet@mailnesia.com
    xwallet.apiKey=9ba9a50feaa0aad6d108fb0827cda3e12f9d2e025f714e6c5927c90e327ec369
    xwallet.connectionTimeout=67000
    xwallet.readTimeout=67000
    xwallet.otpPhrase=pd4frrwgmec64u3pry2nbacpuysvpuw2
    xwallet.walletPassphrase=
    xwallet.checkDeposit.start=false
    xwallet.checkCreateWithdraw.start=false

    # Telegram chatbot
    telegram.apikey=2137248492:AAHXBmYv9DsP2vCDXXJ138IjT--WwAVzF2w
    telegram.chatid=-714004868
    telegram.client=https://api.telegram.org/bot
    telegram.connectTimeout=30000
    telegram.readTimeout=30000

    #MinIO
    minio.accesskey=AKIAIOSFODNN7EXAMPLE
    minio.secretkey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    minio.client.domain=http://${minio.host}:${minio.port}
    minio.web.bucket=dealing-development-bucket
    minion.presignedUrl.expired=1

    #Swagger Open API
    springdoc.api-docs.version=OPENAPI_3_0
    springdoc.api-docs.enabled=true
    springdoc.api-docs.path=/swagger/api-specification
    springdoc.swagger-ui.enabled=false
    springdoc.cache.disabled=true
