apiVersion: v1
kind: Service
metadata:
  name: hibtc-web-socket-cluster-loadbalancer
  namespace: api
spec:
  ports:
    - port: 80
      #nodePort: 30002
      protocol: TCP
      targetPort: 8080
  selector:
    app: hibtc-web-socket
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 172.30.0.102
