apiVersion: v1
kind: Service
metadata:
  name: hibtc-web-socket-cluster-ip-service-1
  namespace: api
  labels:
    app: hibtc-web-socket
    cluster: "1"
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: hibtc-web-socket
    cluster: "1"
    version: "1"
  ports:
    - name: http
      port: 8082
      targetPort: 8080
