apiVersion: v1
kind: Service
metadata:
  name: hibtc-web-socket-cluster-nodeport
  namespace: api
spec:
  selector:
    component: hibtc-web-socket
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30002
      protocol: TCP
