apiVersion: v1
kind: Service
metadata:
  name: hibtc-web-socket-cluster-ip-service
  namespace: api
  labels:
    app: hibtc-web-socket
spec:
  type: ClusterIP
  selector:
    app: hibtc-web-socket
  ports:
    - name: http
      port: 8082
      targetPort: 8080
