apiVersion: v1
kind: Service
metadata:
  name: rmqbroker-cluster-ip-service
  namespace: database
  labels:
    app: rmqbroker
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: rmqbroker
    version: "1"
  ports:
    - name: tcp-10909
      port: 10909
      targetPort: 10909
    - name: tcp-10911
      port: 10911
      targetPort: 10911
