apiVersion: v1
kind: Service
metadata:
  name: rmqnamesrv-cluster-nodeport
  namespace: database
  labels:
    app: rmqnamesrv
spec:
  type: NodePort
  selector:
    app: rmqnamesrv
  ports:
    - port: 9876
      targetPort: 9876
      nodePort: 30876
      protocol: TCP
