apiVersion: v1
kind: Service
metadata:
  name: rmqnamesrv-cluster-ip-service
  namespace: database
  labels:
    app: rmqnamesrv
    version: "1"
spec:
  type: ClusterIP
  selector:
    app: rmqnamesrv
    version: "1"
  ports:
    - name: tcp-9876
      port: 9876
      targetPort: 9876
