apiVersion: v1
kind: Service
metadata:
  name: rmqnamesrv-cluster-loadbalancer
  namespace: database
spec:
  ports:
    - port: 9876
      protocol: TCP
      targetPort: 9876
  selector:
    app: rmqnamesrv
  type: LoadBalancer
  loadBalancerIP: 172.30.0.108
status:
  loadBalancer: {}
